{{ if .customRegistry.enabled -}}
---
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: infrastructure
  name: custom-registry-config
data:
  LOGIN: {{ .customRegistry.login }}
  TOKEN: {{ .customRegistry.token }}
{{- end }}
