{{ if .customRegistry -}}
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: customregistry-pushsecret
  namespace: infrastructure
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
spec:
  encryptedData:
    config.json: {{ .customRegistry.credentials.encryptedDockerconfigjson }}
{{- end }}
