{{ if or .ghcrRegistry.enabled .dockerhubRegistry.enabled -}}
---
apiVersion: v1
kind: Secret
metadata:
  name: dockerconfig-secret
  namespace: infrastructure
type: kubernetes.io/dockerconfigjson
data:
  {{- if .ghcrRegistry.enabled }}
  .dockerconfigjson:  {{- printf "{\"auths\":{\"%s\":{\"auth\":\"ghcr.io\"}}}" (printf "%s:%s" .ghcrRegistry.login .ghcrRegistry.token | b64enc) | b64enc }}
  {{- else if .dockerhubRegistry.enabled }}
  .dockerconfigjson: {{- printf "{\"auths\":{\"%s\":{\"email\":\"https://index.docker.io/v1/\",\"auth\":\"%s\"}}}" .dockerhubRegistry.email (printf "%s:%s" .dockerhubRegistry.login .dockerhubRegistry.token | b64enc) | b64enc }}
  {{- end }}
{{- end }}
