{{ if .dockerhubRegistry -}}
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: dockerhubregistry-pushsecret
  namespace: infrastructure
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
spec:
  encryptedData:
    config.json: {{ .dockerhubRegistry.credentials.encryptedDockerconfigjson }}
{{- end }}
