{{ if or .ghcrRegistry.enabled .dockerhubRegistry.enabled -}}
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: dockerconfig-secret
  namespace: infrastructure
  labels:
    helm.sh/chart: onechart-0.64.0
    app.kubernetes.io/name: onechart
    app.kubernetes.io/instance: dockerconfig-secret
    app.kubernetes.io/managed-by: Helm
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
spec:
  encryptedData:
    {{- if .ghcrRegistry.enabled }}
    .dockerconfigjson: {{ printf '{\"auths\":{\"ghcr.io\":{\"auth\":\"%s\"}}}' (printf "%s:%s" .ghcrRegistry.login .ghcrRegistry.token | b64enc) }}
    {{- else if .dockerhubRegistry.enabled }}
    .dockerconfigjson: {{ printf '{\"auths\":{\"https://index.docker.io/v1/\":{\"email\":\"%s\",\"auth\":\"%s\"}}}' .dockerhubRegistry.email (printf "%s:%s" .dockerhubRegistry.login .dockerhubRegistry.token | b64enc) }}
    {{- end }}
  template:
    metadata:
      name: dockerconfig-secret
      namespace: infrastructure
{{- end }}
