{{ if .ghcrRegistry -}}
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ghcrregistry-pushsecret
  namespace: infrastructure
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
spec:
  encryptedData:
    config.json: {{ .ghcrRegistry.credentials.encryptedDockerconfigjson }}
{{- end }}
