{{ if .ghcrRegistry.enabled -}}
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ghcr-registry-secret
  namespace: infrastructure
  labels:
    helm.sh/chart: onechart-0.64.0
    app.kubernetes.io/name: onechart
    app.kubernetes.io/instance: dockerconfig-secret
    app.kubernetes.io/managed-by: Helm
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
spec:
  encryptedData:
    .dockerconfigjson: {{ .ghcrRegistry.encryptedDockerconfigjson }}
  template:
    metadata:
      name: dockerconfig-secret
      namespace: infrastructure
{{- end }}
