{{ if or .loki.enabled .prometheus.enabled -}}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: infrastructure-grafana-datasources
  namespace: infrastructure
  labels:
    grafana_datasource: "1"
data:
  datasources.yaml: |-
    apiVersion: 1
    datasources:
    {{- if .loki.enabled }}
    - name: Loki
      type: loki
      access: proxy
      url: http://loki:3100
      version: 1
      uid: loki
      {{- if .tempo.enabled }}
      jsonData:
        derivedFields:
          - name: "traceId"
            matcherRegex: "traceId (\\w+)"
            url: "$${__value.raw}"
            datasourceUid: tempo
      {{- end }}
    {{- end }}
    {{- if .prometheus.enabled }}
    - name: Prometheus
      type: prometheus
      access: proxy
      url: http://prometheus-server:80
      version: 1
    {{- end }}
    {{- if .tempo.enabled }}
    - name: Tempo
      type: tempo
      access: proxy
      url: http://tempo:3100
      version: 1
      uid: tempo
      jsonData: {
            "tracesToLogs": {
                "datasourceUid": "loki",
                "tags": [
                    "instance"
                ]
            }
        }
    {{- end }}
{{- end }}
