---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: aws-efs-csi-driver
  namespace: kube-system
spec:
  interval: 60m
  url: https://kubernetes-sigs.github.io/aws-efs-csi-driver/
