{{ if .externalSecrets.enabled -}}
---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: external-secrets
  namespace: infrastructure
spec:
  interval: 60m
  url: https://charts.external-secrets.io
{{- end }}
