{{ if .tofuController.enabled -}}
---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: tofu-controller
  namespace: flux-system
spec:
  interval: 60m
  url: https://flux-iac.github.io/tofu-controller
{{- end }}
