{{ if .aws.enabled -}}
---
apiVersion: v1
kind: Secret
metadata:
  name: aws-account-creds
  namespace: infrastructure
type: Opaque
data:
  credentials: {{ .crossplane.awsCredentials }}
---
apiVersion: aws.crossplane.io/v1beta1
kind: ProviderConfig
metadata:
  name: default
spec:
  credentials:
    source: Secret
    secretRef:
      namespace: infrastructure
      name: aws-account-creds
      key: credentials
{{- end }}
