---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: aws-ebs-csi-driver
  namespace: kube-system
spec:
  interval: 60m
  releaseName: aws-ebs-csi-driver
  chart:
    spec:
      chart: aws-ebs-csi-driver
      version: 2.4.0
      sourceRef:
        kind: HelmRepository
        name: aws-ebs-csi-driver
      interval: 10m
  values:
    controller:
      logLevel: 3
      serviceAccount:
        create: true
        name: ebs-csi-controller-sa
        annotations:
          eks.amazonaws.com/role-arn: arn:aws:iam::782027979363:role/ebs-csi-driver-role
