{{ if .certManager.enabled -}}
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cert-manager
  namespace: infrastructure
spec:
  interval: 60m
  releaseName: cert-manager
  chart:
    spec:
      chart: cert-manager
      version: v1.6.1
      sourceRef:
        kind: HelmRepository
        name: jetstack
      interval: 10m
  values:
    installCRDs: true
    {{- if .linkerd.enabled }}
    deploymentAnnotations:
      linkerd.io/inject: disabled
    {{- end }}
{{- end }}
