{{ if .externalSecrets.enabled -}}
---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: external-secrets
  namespace: infrastructure
spec:
  interval: 60m
  releaseName: external-secrets-controller
  chart:
    spec:
      chart: external-secrets
      version: 0.9.11
      sourceRef:
        kind: HelmRepository
        name: external-secrets
      interval: 10m
  values: {}
{{- end }}
