{{ if .gimletAgent.enabled -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: gimlet-agent
  namespace: infrastructure
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: gimlet-agent
rules:
- apiGroups:
    - networking.k8s.io
    - ""
  resources:
    - pods
    - pods/log
    - ingresses
    - services
    - events
  verbs:
    - get
    - watch
    - list
- apiGroups:
    - apps
  resources:
    - deployments
  verbs:
    - get
    - watch
    - list
    - patch # to allow restarting of deployments
- apiGroups:
    - batch
  resources:
    - jobs
  verbs:
    - create
- apiGroups:
    - source.toolkit.fluxcd.io
    - kustomize.toolkit.fluxcd.io
    - helm.toolkit.fluxcd.io
  resources:
    - gitrepositories
    - ocirepositories
    - buckets
    - kustomizations
    - helmreleases
  verbs:
    - get
    - watch
    - list
    - patch # to allow force reconciling by adding an annotation
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: gimlet-agent
subjects:
  - kind: ServiceAccount
    name: gimlet-agent
    namespace: infrastructure
roleRef:
  kind: ClusterRole
  name: gimlet-agent
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: gimlet-agent
  namespace: infrastructure
spec:
  interval: 60m
  releaseName: gimlet-agent
  chart:
    spec:
      chart: onechart
      version: 0.66.0
      sourceRef:
        kind: HelmRepository
        name: onechart
      interval: 10m
  values:
    serviceAccount: gimlet-agent
    image:
      repository: ghcr.io/gimlet-io/gimlet
      tag: agent-v1.0.0-alpha.23
      pullPolicy: IfNotPresent
    vars:
      HOST: {{ .gimletAgent.dashboardAddress }}
      AGENT_KEY: {{ .gimletAgent.agentKey }}
      ENV: {{ .gimletAgent.environment }}
    resources:
      requests:
        cpu: "100m"
        memory: "200Mi"
      limits:
        cpu: "500m"
        memory: "500Mi"
    {{- if .linkerd.enabled }}
    podAnnotations:
      linkerd.io/inject: disabled
      prometheus.io/port: "9002"
      prometheus.io/scrape: "true"
    {{- end }}
{{- end }}
