{{ if .gimletd.enabled -}}
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: gimletd
  namespace: infrastructure
spec:
  interval: 60m
  releaseName: gimletd
  chart:
    spec:
      chart: onechart
      version: 0.35.0
      sourceRef:
        kind: HelmRepository
        name: onechart
      interval: 10m
  values:
    image:
      repository: ghcr.io/gimlet-io/gimletd
      tag: v0.9.0
      pullPolicy: Always
    containerPort: 8888
    probe:
      enabled: true
      path: /
    volumes:
      {{- if not .gimletd.postgresql.password }}
      - name: data
        path: /var/lib/gimletd
        size: 1Gi
      {{- end }}
      - name: repo-cache
        path: /tmp/gimletd
        size: 5Gi
    ingress:
      annotations:
        kubernetes.io/ingress.class:  {{ default false .nginx.enabled | ternary "nginx" "traefik" }}
        {{- if .certManager.enabled }}
        cert-manager.io/cluster-issuer: letsencrypt
        {{- end }}
      host: gimletd.{{ default false .nginx.enabled | ternary .nginx.host .civo.host }}
      tlsEnabled: true
    vars:
      PRINT_ADMIN_TOKEN: true
      GITOPS_REPO: {{ .gimletd.gitopsRepo }}
      GITOPS_REPO_DEPLOY_KEY_PATH: /github/deploy.key
      ADMIN_TOKEN: {{ .gimletd.adminToken }}
      {{- if .gimletd.postgresql.password }}
      DATABASE_DRIVER: postgres
      DATABASE_CONFIG: "postgres://{{ .gimletd.postgresql.user }}:{{ .gimletd.postgresql.password }}@{{ .gimletd.postgresql.hostAndPort }}/{{ .gimletd.postgresql.db }}?sslmode=disable"
      {{- end }}
    fileSecrets:
      - name:  github-gitops-deploy-key
        path: /github
        secrets:
          deploy.key: |
{{ indent 12 .gimletd.deployKey }}
    resources:
      requests:
        cpu: "50m"
        memory: "200Mi"
      limits:
        cpu: "2000m"
        memory: "1000Mi"
{{- end }}
