{{ if .gimletAgent.enabled -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: gimlet-agent
  namespace: infrastructure
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: gimlet-agent
subjects:
  - kind: ServiceAccount
    name: gimlet-agent
    namespace: infrastructure
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: gimlet-agent
  namespace: infrastructure
spec:
  interval: 60m
  releaseName: gimlet-agent
  chart:
    spec:
      chart: onechart
      version: 0.38.0
      sourceRef:
        kind: HelmRepository
        name: onechart
      interval: 10m
  values:
    serviceAccount: gimlet-agent
    image:
      repository: ghcr.io/gimlet-io/gimlet-dashboard
      tag: agent-v0.10.0-rc.2
      pullPolicy: Always
    vars:
      HOST: {{ .gimletAgent.dashboardAddress }}
      AGENT_KEY: {{ .gimletAgent.agentKey }}
      ENV: {{ .gimletAgent.environment }}
    resources:
      requests:
        cpu: "100m"
        memory: "200Mi"
      limits:
        cpu: "500m"
        memory: "500Mi"
    {{- if .linkerd.enabled }}
    podAnnotations:
      linkerd.io/inject: disabled
    {{- end }}
{{- end }}
