{{ if or (or .loki.enabled .prometheus.enabled) .tempo.enabled -}}
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: grafana
  namespace: infrastructure
spec:
  interval: 60m
  releaseName: grafana
  chart:
    spec:
      chart: grafana
      version: 6.31.2
      sourceRef:
        kind: HelmRepository
        name: grafana
      interval: 10m
  values:
    sidecar:
      datasources:
        enabled: true
      dashboards:
        enabled: true
      notifiers:
        enabled: true
    {{- if or .nginx.enabled .civo.enabled}}
    ingress:
      enabled: true
      ingressClassName: {{ default false .nginx.enabled | ternary "nginx" "traefik" }}
      {{- if .certManager.enabled }}
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt
      tls:
        - secretName: tls-grafana
          hosts:
            - grafana.{{ default false .nginx.enabled | ternary .nginx.host .civo.host }}
      {{- end }}
      hosts:
        - grafana.{{ default false .nginx.enabled | ternary .nginx.host .civo.host }}
      path: /
    {{- end }}
{{- end }}
