{{ if or .keda.enabled -}}
---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: keda
  namespace: infrastructure
spec:
  interval: 60m
  releaseName: keda
  chart:
    spec:
      chart: keda
      version: 2.9.3
      sourceRef:
        kind: HelmRepository
        name: keda
      interval: 10m
{{- end }}
