{{ if .kyverno.enabled -}}
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kyverno
  namespace: infrastructure
spec:
  interval: 60m
  releaseName: kyverno
  chart:
    spec:
      chart: kyverno
      version: v2.3.2
      sourceRef:
        kind: HelmRepository
        name: kyverno
      interval: 10m
  values:
    podAnnotations:
      prometheus.io/port: "8000"
      prometheus.io/scrape: "true"
    extraArgs:
    - --background-scan=30s
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kyverno-policies
  namespace: infrastructure
spec:
  interval: 60m
  releaseName: kyverno-policies
  chart:
    spec:
      chart: kyverno-policies
      version: v2.3.1
      sourceRef:
        kind: HelmRepository
        name: kyverno
      interval: 10m
  values:
    podSecurityStandard: {{ .kyverno.podSecurityStandard }}
    validationFailureAction: audit
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kyverno-policy-reporter
  namespace: infrastructure
spec:
  interval: 60m
  releaseName: kyverno-policy-reporter
  chart:
    spec:
      chart: policy-reporter
      version: 2.7.0
      sourceRef:
        kind: HelmRepository
        name: kyverno-policy-reporter
      interval: 10m
  values:
    podAnnotations:
      prometheus.io/port: "2112"
      prometheus.io/scrape: "true"
{{- end }}
