{{ if .kyverno.enabled -}}
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kyverno-crds
  namespace: infrastructure
spec:
  interval: 60m
  releaseName: kyverno-crds
  chart:
    spec:
      chart: kyverno-crds
      version: v2.0.3
      sourceRef:
        kind: HelmRepository
        name: kyverno
      interval: 10m
  values:
    installCRDs: true
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kyverno
  namespace: infrastructure
spec:
  interval: 60m
  releaseName: kyverno
  chart:
    spec:
      chart: kyverno
      version: v2.0.3
      sourceRef:
        kind: HelmRepository
        name: kyverno
      interval: 10m
  values:
    podSecurityStandard: {{ .kyverno.podSecurityStandard }}
    validationFailureAction: audit
    podAnnotations:
      prometheus.io/port: "8000"
      prometheus.io/scrape: "true"
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kyverno-policy-reporter
  namespace: infrastructure
spec:
  interval: 60m
  releaseName: kyverno-policy-reporter
  chart:
    spec:
      chart: policy-reporter
      version: 1.12.6
      sourceRef:
        kind: HelmRepository
        name: kyverno-policy-reporter
      interval: 10m
  values:
    podAnnotations:
      prometheus.io/port: "2112"
      prometheus.io/scrape: "true"
{{- end }}
