{{ if .loki.enabled -}}
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: loki
  namespace: infrastructure
spec:
  interval: 60m
  releaseName: loki
  chart:
    spec:
      chart: loki
      version: 2.10.3
      sourceRef:
        kind: HelmRepository
        name: grafana
      interval: 10m
  values:
    {{ if .loki.persistence -}}
    persistence:
      enabled: true
      size: {{ default 10 .loki.volumeSize -}}Gi
    {{- end }}
    config:
      auth_enabled: false
      ingester:
        chunk_idle_period: 3m
        chunk_block_size: 262144
        chunk_retain_period: 1m
        max_transfer_retries: 0
        lifecycler:
          ring:
            kvstore:
              store: inmemory
            replication_factor: 1
      limits_config:
        enforce_metric_name: false
        reject_old_samples: true
        reject_old_samples_max_age: 168h
      schema_config:
        configs:
          - from: "2020-10-24"
            store: boltdb-shipper
            object_store: filesystem
            schema: v11
            index:
              prefix: index_
              period: 24h
      server:
        http_listen_port: 3100
      storage_config:
        boltdb_shipper:
          active_index_directory: /data/loki/boltdb-shipper-active
          cache_location: /data/loki/boltdb-shipper-cache
          cache_ttl: 24h         # Can be increased for faster performance over longer query periods, uses more disk space
          {{ if .loki.storage.retentionDays -}}
          shared_store: filesystem
          {{- end }}
          {{ if .loki.storage.s3Url -}}
          shared_store: s3
          {{- end }}
        {{ if .loki.storage.retentionDays -}}
        filesystem:
          directory: /data/loki/chunks
        {{- end }}
        {{ if .loki.storage.s3Url -}}
        aws:
          s3: "{{ .loki.storage.s3Url }}"
          bucketnames: {{ .loki.storage.bucketName }}
        {{- end }}
      chunk_store_config:
        max_look_back_period: 0s
      {{ if .loki.storage.retentionDays -}}
      table_manager:
        retention_deletes_enabled: true
        retention_period: {{ mul 24 (default 14 .loki.storage.retentionDays) }}h
      {{- end }}
      compactor:
        working_directory: /data/loki/boltdb-shipper-compactor
        shared_store: filesystem
{{- end }}
