{{ if .loki.enabled -}}
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: loki
  namespace: infrastructure
spec:
  interval: 60m
  releaseName: loki
  chart:
    spec:
      chart: loki
      version: 5.41.7
      sourceRef:
        kind: HelmRepository
        name: grafana
      interval: 10m
  valuesFrom:
  - kind: Secret
    name: loki-azure-credentials
    valuesKey: accountname
    targetPath: loki.storage.azure.accountName
  - kind: Secret
    name: loki-azure-credentials
    valuesKey: accountkey
    targetPath: loki.storage.azure.accountKey
  values:
    test:
      enabled: false
    minio:
      enabled: false
    gateway:
      enabled: false
    monitoring:
      lokiCanary:
        enabled: false
      selfMonitoring:
        enabled: false
        grafanaAgent:
          installOperator: false
          enableConfigReadAPI: false
      serviceMonitor:
        enabled: false
      alerts:
        enabled: false
      rules:
        enabled: false
        alerting: true
      dashboards:
        enabled: false
    singleBinary:
      extraArgs:
        - -config.expand-env=true
      replicas: 1
      resources:
        limits:
          cpu: 1000m
          memory: 2000Mi
        requests:
          cpu: 100m
          memory: 2000Mi
    loki:
      podAnnotations:
        linkerd.io/inject: disabled
      tracing:
        enabled: false
      containerSecurityContext:
        allowPrivilegeEscalation: false
      {{ if .loki.config.authentication -}}
      auth_enabled: {{ .loki.config.authentication.enabled }}
      {{- end }}
      commonConfig:
      {{ if .loki.config.replication_factor -}}
        replication_factor: 1
      {{- end }}
      {{ if .loki.storage -}}
      storage:
        {{ if .loki.storage.azure -}}
        bucketNames:
          chunks: {{ .loki.storage.azure.bucket }}
        type: "azure"
        {{- end }}
      {{- end }}
      querier:
        engine:
          timeout: 5m
      limits:
        query_timeout: 5m
      ingester:
        chunk_idle_period: 60m
        chunk_block_size: 200000000
        chunk_target_size: 8000000
        chunk_encoding: snappy
        lifecycler:
          ring:
            kvstore:
              store: inmemory
            replication_factor: 1
      limits_config:
        enforce_metric_name: false
      memcached:
        chunk_cache:
          enabled: true
          host: memcached.infrastructure.svc.cluster.local
          service: memcache
          batch_size: 2048
          parallelism: 1
        results_cache:
          enabled: true
          host: memcached.infrastructure.svc.cluster.local
          service: "memcache"
          timeout: "500ms"
      schemaConfig:
        configs:
        - from: "2020-10-24"
          store: boltdb-shipper
          object_store: azure
          schema: v11
          index:
            prefix: index_
            period: 24h
      compactor:
        shared_store: azure
        compaction_interval: 100m
{{- end }}
{{ if .loki.storage.azure -}}
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: loki-azure-credentials
  namespace: infrastructure
spec:
  encryptedData:
    accountname: {{ .loki.storage.azure.accountname }}
    accountkey:  {{ .loki.storage.azure.accountkey }}
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: loki-azure-credentials
      namespace: infrastructure
{{- end }}
