{{ if .loki.enabled -}}
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: loki
  namespace: infrastructure
spec:
  interval: 60m
  releaseName: loki
  chart:
    spec:
      chart: loki
      version: 5.41.7
      sourceRef:
        kind: HelmRepository
        name: grafana
      interval: 10m
  values:
    test:
      enabled: false
    minio:
      enabled: false
    gateway:
      enabled: false
    monitoring:
      lokiCanary:
        enabled: false
      selfMonitoring:
        enabled: false
        grafanaAgent:
          installOperator: false
          enableConfigReadAPI: false
      serviceMonitor:
        enabled: false
      alerts:
        enabled: false
      rules:
        enabled: false
        alerting: true
      dashboards:
        enabled: false
    singleBinary:
      extraArgs:
        - -config.expand-env=true
      replicas: 1
      {{ if .loki.persistence -}}
      persistence:
        enabled: true
        size: {{ default 10 .loki.volumeSize -}}Gi
      {{- end }}
    loki:
      tracing:
        enabled: false
      containerSecurityContext:
        allowPrivilegeEscalation: false
        readOnlyRootFilesystem: false
      auth_enabled: false
      commonConfig:
        replication_factor: 1
      querier:
        engine:
          timeout: 5m
      limits:
        query_timeout: 5m
      ingester:
        chunk_idle_period: 60m
        chunk_block_size: 200000000
        chunk_target_size: 8000000
        chunk_encoding: snappy
        lifecycler:
          ring:
            kvstore:
              store: inmemory
            replication_factor: 1
      limits_config:
        enforce_metric_name: false
      schemaConfig:
        configs:
        - from: "2020-10-24"
          store: boltdb-shipper
          object_store: filesystem
          schema: v11
          index:
            prefix: index_
            period: 24h
      compactor:
        shared_store: filesystem
        compaction_interval: 100m
{{- end }}
