{{ if .namespaces -}}
{{ $length := len .namespaces -}}
{{ if gt $length 0 -}}
---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: namespaces
  namespace: infrastructure
spec:
  interval: 60m
  releaseName: namespaces
  chart:
    spec:
      chart: namespaces
      version: 0.3.0
      sourceRef:
        kind: HelmRepository
        name: onechart
      interval: 10m
  values:
    namespaces:
      {{- range $idx, $namespace := .namespaces.namespaces }}
      - name: {{ $namespace.name }}
      {{- end }}
{{- end }}
{{- end }}
