{{ if .namespaces.enabled -}}
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: namespaces
  namespace: infrastructure
spec:
  interval: 60m
  releaseName: namespaces
  chart:
    spec:
      chart: namespaces
      version: 0.2.0
      sourceRef:
        kind: HelmRepository
        name: onechart
      interval: 10m
  values:
    {{- range $idx, $namespace := .namespaces.namespaces }}
    {{ $idx }}-namespace: {{ $namespace.name }}
    {{- end }}
{{- end }}
