{{ if .namespaces.enabled -}}
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: namespaces
  namespace: infrastructure
spec:
  interval: 60m
  releaseName: namespaces
  chart:
    spec:
      chart: namespaces
      version: 0.2.0
      sourceRef:
        kind: HelmRepository
        name: onechart
      interval: 10m
  values:
    namespaces:
      {{- range $idx, $namespace := .namespaces.namespaces }}
      - name: {{ $namespace.name }}
        namespace:
          budget:
            cpu: 32
            memory: "64Gi"
            storage: "500Gi"
          overcommit:
            cpu: 2
            memory: 1
        pod:
          limits:
            cpu: 4
            memory: "8Gi"
          defaults:
            cpu: "200m"
            memory: "200Mi"
          overcommit:
            cpu: 10
            memory: 2
      {{- end }}
{{- end }}
