# Source: onechart/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: namespaces
  namespace: preview
  labels:
    helm.sh/chart: onechart-0.32.0
    app.kubernetes.io/name: onechart
    app.kubernetes.io/instance: namespaces
    app.kubernetes.io/managed-by: Helm
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
    
  selector:
    app.kubernetes.io/name: onechart
    app.kubernetes.io/instance: namespaces
---
# Source: onechart/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: namespaces
  namespace: preview
  labels:
    helm.sh/chart: onechart-0.32.0
    app.kubernetes.io/name: onechart
    app.kubernetes.io/instance: namespaces
    app.kubernetes.io/managed-by: Helm
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: onechart
      app.kubernetes.io/instance: namespaces
  template:
    metadata:
      annotations:
        checksum/config: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
      labels:
        app.kubernetes.io/name: onechart
        app.kubernetes.io/instance: namespaces
    spec:
      securityContext:
        fsGroup: 999
      containers:
        - name: namespaces
          securityContext: &securityContext
            {}
          image: "nginx:latest"
          imagePullPolicy: IfNotPresent
          
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
            
          
          resources:
            limits:
              cpu: 200m
              memory: 200Mi
            requests:
              cpu: 200m
              memory: 200Mi
