{{ if .loki.enabled -}}
---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: promtail
  namespace: infrastructure
spec:
  interval: 60m
  releaseName: promtail
  chart:
    spec:
      chart: promtail
      version: 6.15.3
      sourceRef:
        kind: HelmRepository
        name: grafana
      interval: 10m
  values:
    config:
      clients:
        - url: "http://loki:3100/loki/api/v1/push"
{{- end }}
