{{ if .prometheus.enabled -}}
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: prometheus-node-exporter
  namespace: infrastructure
spec:
  interval: 60m
  releaseName: prometheus-node-exporter
  chart:
    spec:
      chart: prometheus-node-exporter
      version: 4.25.0
      sourceRef:
        kind: HelmRepository
        name: prometheus
      interval: 10m
  values:
    resources:
      limits:
        cpu: 1000m
        memory: 250Mi
      requests:
        cpu: 100m
        memory: 250Mi
    containerSecurityContext:
      readOnlyRootFilesystem: true
      allowPrivilegeEscalation: false
{{- end }}
