{{ if .sealedSecrets.enabled -}}
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: sealed-secrets
  namespace: infrastructure
spec:
  interval: 60m
  releaseName: sealed-secrets-controller
  chart:
    spec:
      chart: sealed-secrets
      version: 2.13.4
      sourceRef:
        kind: HelmRepository
        name: sealed-secrets
      interval: 10m
  values:
    containerSecurityContext:
      allowPrivilegeEscalation: false
    resources:
      limits:
        cpu: 1000m
        memory: 150Mi
      requests:
        cpu: 10m
        memory: 25Mi
    keyrenewperiod: "0"
{{- end }}
