{{ if .tempo.enabled -}}
---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: tempo
  namespace: infrastructure
spec:
  interval: 60m
  releaseName: tempo
  chart:
    spec:
      chart: tempo
      version: 0.15.4
      sourceRef:
        kind: HelmRepository
        name: grafana
      interval: 10m
  values:
    installCRDs: true
{{- end }}
