---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: prometheus
  namespace: infrastructure
spec:
  interval: 60m
  url: https://prometheus-community.github.io/helm-charts
