---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: prometheus
  namespace: infrastructure
spec:
  interval: 60m
  releaseName: prometheus
  chart:
    spec:
      chart: prometheus
      version: 14.7.1
      sourceRef:
        kind: HelmRepository
        name: prometheus
      interval: 10m
  values:
    pushgateway:
      enabled: false
    alertmanager:
      enabled: false
    kube-state-metrics:
      metricLabelsAllowlist:
        - pods=[app.kubernetes.io/name,app.kubernetes.io/component,app.kubernetes.io/instance]
        - deployments=[app.kubernetes.io/name,app.kubernetes.io/component,app.kubernetes.io/instance]
    server:
      strategy:
        type: Recreate
      retention: "14d"
      global:
        scrape_interval: 15s
    extraScrapeConfigs: |-
